Repository juulabel/juulabel-back, pull requests merged in 2024-12, with the labels that each got.

#74 PR : 용량에 따른 가격 추가
  src/main/java/com/juu/juulabel/api/dto/response/AlcoholicDrinksDetailResponse.java
  src/main/java/com/juu/juulabel/api/service/alcohol/AlcoholicDrinksService.java
  src/main/java/com/juu/juulabel/domain/dto/alcohol/VolumePriceDetail.java
  src/main/java/com/juu/juulabel/domain/repository/query/AlcoholDrinksDetailQueryRepository.java
  src/main/java/com/juu/juulabel/domain/repository/reader/AlcoholicDrinksReader.java
Labels: [REFACTOR], [FEAT]

#76 PR : sse 에러 해결
  build.gradle
Labels: [CHORE], [FIX]

#77 PR : OD 시음노트 삭제 시 NaN 에러 해결
  src/main/java/com/juu/juulabel/domain/entity/alcohol/AlcoholicDrinks.java
Labels: [FIX]
