Repository juulabel/juulabel-back, pull requests merged in 2025-03, with the labels that each got.

#101 PR : 이미지 없이 프로필 수정 시 null 처리되는 버그 해결
  src/main/java/com/juu/juulabel/api/service/member/MemberService.java
  src/main/java/com/juu/juulabel/domain/entity/member/Member.java
Labels: [FIX]

#105 PR : 핫픽스 해결
  src/main/java/com/juu/juulabel/api/config/SecurityConfig.java
  src/main/java/com/juu/juulabel/api/dto/response/MySpaceResponse.java
  src/main/java/com/juu/juulabel/api/service/member/MemberService.java
  src/main/java/com/juu/juulabel/api/service/s3/S3Uploader.java
  src/main/java/com/juu/juulabel/common/exception/code/ErrorCode.java
  src/main/java/com/juu/juulabel/domain/repository/query/TastingNoteQueryRepository.java
  src/test/java/com/juu/juulabel/api/service/s3/S3UploaderTest.java
Labels: [FIX], [FEAT]

#110 PR : 토큰 관련 예외 처리
  src/main/java/com/juu/juulabel/api/filter/JwtAuthenticationFilter.java
  src/main/java/com/juu/juulabel/common/exception/code/ErrorCode.java
  src/main/java/com/juu/juulabel/common/exception/handler/GlobalExceptionHandler.java
Labels: [REFACTOR]

#114 PR : Sentry 에러 모니터링 추가
  build.gradle
  src/main/java/com/juu/juulabel/common/exception/handler/GlobalExceptionHandler.java
Labels: [REFACTOR], [FEAT]

#123 [#253] feat : 팔로워 삭제 오류해결
  src/main/java/com/juu/juulabel/api/service/follow/FollowService.java
Labels: [REFACTOR], [FEAT]
